site_name: Git Engineering Handbook
site_url: https://githandbook.rayhanhossen.pro
site_description: Professional Git workflow documentation
site_author: Rayhan Hossen

repo_name: rayhanhossen/git-engineering-handbook
repo_url: https://github.com/rayhanhossen/git-engineering-handbook

copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> Rayhan Hossen

theme:
  name: material
  icon:
    logo: fontawesome/brands/git-alt

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rayhanhossen
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/rayhanhossen
      name: LinkedIn
    - icon: fontawesome/solid/globe
      link: https://rayhanhossen.pro
      name: Portfolio

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed

nav:
  - Home: index.md
  - Why Git: why-git.md
  - Git Basics: basics.md
  - Basic Commands: basic-commands.md
  - Advanced Commands: advanced-commands.md
  - Branching Strategy: branching-strategy.md
  - Commit Strategy: commit-strategy.md
  - CI/CD Pipelines: ci-cd-pipelines.md
  - Cheat Sheet: cheat-sheet.md